### ISSUE TITLE
Can't operate with products after changing IDM to HTTPS!

### ISSUE THREAD

**Issue by emepetres** [FIWARE-TMForum/Business-API-Ecosystem#24]
Hi, after changing IDM to https, "old" products and offerings can not be updated nor operated with them (If we create a new product everything works as expected). We also changed marketplace from port 8004 to port 80, but I guess that is not related to it. We are using latest docker develop images.

This is a critical problem for us right now!!

![marketplace_bug](https://user-images.githubusercontent.com/1446793/41276338-40773546-6e24-11e8-8a67-920218ff5091.PNG)
![marketplace_bug2](https://user-images.githubusercontent.com/1446793/41276343-424cfbbc-6e24-11e8-8fcf-7cefa2b80aa8.PNG)
![marketplace_bug3](https://user-images.githubusercontent.com/1446793/41276350-45db9b26-6e24-11e8-91f0-ee46214d0539.PNG)
<img width="716" alt="marketplace_bug4" src="https://user-images.githubusercontent.com/1446793/41276369-56c4fad6-6e24-11e8-9f8d-6c6ec24cb8bb.png">

**Comment by fdelavega** [comment]
The problem is that all the objects within the BAE include an HREF which is generated using the configured host of the system.

If the host of the platform is changed, new calculated HREF are not the same as the one saved with the object, so it gives an unauthorized error since it thoughts you are trying to access a different object.

The only solution is migrating the databases to adapt the old HREFs to the new ones

**Comment by Trophime** [comment]
Can we handle this? I mean the migration...

**Comment by fdelavega** [comment]
Yes, First of all, make a dump of the databases and save it.

Then you can just copy the dump, make a search of the old HREF host, replace by the new one and load the SQLs files

But save the dump of the current status, just in case...

**Comment by emepetres** [comment]
Finally we resolved it deleting recreating all databases again, and therefore deleting all data.
