### ISSUE TITLE
Keyrock OAuth2 callback redirect could be configurable

### ISSUE THREAD

**Issue by emepetres** [FIWARE-TMForum/Business-API-Ecosystem#4]
In order to make the system "embed-able" by other webs (let's say the biz-ecosystem as a subsystem of a bigger web application) the redirect call of the /auth/fiware/callback request should be configurable, so it could redirect to the parent website instead of the biz-ecosystem. This way the biz-ecosystem could be embedded as follows:
Parent web calls /login; the biz-ecosystem logs in and redirects to parent web again, where the biz-ecosystem will be present as an iframe. 

The redirect path could be set (not required) in config.js and also through docker-compose.

Apart from that, the Sign In button could add target="_top" to allow user sign in inside an iframe.

**Comment by fdelavega** [comment]
At this moment, the portal redirects to the page the user was trying to access (or the home if the login started as a click in the Sign in button).

If I have understood correctly, you need a flag in config.js that enables the portal to finish the login process in a custom web page.

We have to think about this feature in order to incorporate it into the roadmap; nevertheless, we accept pull requests, so If you develop this before as part of you integration, please consider contributing it.
